use_gaden: true
use_slam: true
scene: warehouse
use_rviz: true
headless: false
scene_config: scenes/warehouse/scene.yaml
mission_manager_delay: 15.0
gaden_sensor_gate_timeout: 60.0
gaden_sensor_gate_poll_period: 0.5
use_bt: false
